# Generated by Django 3.1.3 on 2020-11-04 15:08

import computedfields.resolver
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion_item', models.CharField(max_length=255)),
                ('Valor_unidad', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('Razon_social', models.CharField(max_length=255)),
                ('Nit', models.CharField(max_length=15, validators=[home.models.only_int])),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad_item', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('Fecha_E', models.DateTimeField(default=django.utils.timezone.now)),
                ('Valor_neto_sin', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('Valor_iva', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('Valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('ActItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.item')),
                ('Emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emisor_set', to='home.persona')),
                ('Receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor_set', to='home.persona')),
            ],
            options={
                'unique_together': {('Emisor', 'Receptor')},
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
    ]
