# Generated by Django 3.1.3 on 2020-11-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='prueba',
            field=models.CharField(default='Hola', editable=False, max_length=10),
        ),
    ]
